enableGlobalCache: true

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.com"

npmScopes:
  bricksandbraces:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
  openbricksandbraces:
    npmAlwaysAuth: true
    npmRegistryServer: "https://registry.npmjs.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-bump.cjs
    spec: "https://github.com/cometkim/yarn-plugin-bump/releases/download/v0.0.7/plugin-bump.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
